### ISSUE TITLE
Cannot import Tuple2 in NewEnv or fileManipulations in Terraintools

### ISSUE THREAD

**Issue by mtrazzi** [p76dub/MOSIMA-Duel#1]
The import "import dataStructures.tuple.Tuple2;" line 60 file [MOSIMA-Duel/src/env/jme/NewEnv.java](https://github.com/p76dub/MOSIMA-Duel/blob/master/src/env/jme/NewEnv.java) doesn't quite work becaue there doesn't seem to be any "datastructures package".

Similarly, I don't see any fileManipulations for "import fileManipulations.FileManipulations;", in [MOSIMA-Duel/src/env/terrain/TerrainTools.java](https://github.com/p76dub/MOSIMA-Duel/blob/master/src/env/terrain/TerrainTools.java)

**Comment by p76dub** [comment]
The project requires many libraries, including this one you can't find on the web :
[sma-tools.zip](https://github.com/p76dub/MOSIMA-Duel/files/2726518/sma-tools.zip)
